### PR TITLE
Use the correct ticket increments in the cart

### LINKED ISSUE #123: Production Bug: Purchase: Validation error when carting 4-pack ticket type via app - for Mickey Lion TONIGHT
Event: Mickey Lion <https://www.bigneon.com/admin/events/9f5d98c3-d7b6-45a2-8092-cd3622dd2e8e/dashboard> (Tonight)

Issue: Customers cannot purchase the FOUR PACK Ticket Type while using the Big Neon App

Steps to reproduce

1.Open Big Neon App (Not web)

2.Locate Mickey Lion <https://www.bigneon.com/events/mikey-lion-desert-hearts-j-phlip-dirtybird-gorje-hewek-izhevski-adid> Event

3. Select the FOUR PACK Ticket Type and you will get the Validation Error (Screenshot attached)

Please note that you can cart and purchase tickets for this event via Desktop/Web

### PR DESCRIPTION
**Pull request by Krakaw**
Closes #123 

Increment the cart ticket increment by the ticket type increment.

### CODE REVIEW

File: src/state/cartStateProvider.js [hunk 1]
```diff
@@ -122,6 +122,12 @@ class CartContainer extends Container {
         return 0
     }
 
+    get ticketIncrement() {
+        const {increment = 1} = this.selectedTicket;
+        console.log(increment);
```
Comment (Krakaw) [inline src/state/cartStateProvider.js]:
```suggestion
```
